require:
  - rubocop
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
# be a bit kinder with our metrics
Metrics/BlockLength:
  Max: 100
Metrics/MethodLength:
  CountAsOne: ["array", "heredoc", "hash"]
RSpec/MultipleExpectations:
  Enabled: false
RSpec/FilePath:
  SpecSuffixOnly: true
RSpec/MultipleMemoizedHelpers:
  Max: 10
