version: '3'
services:
  web:
    build:
      context: .
      args:
        RUBY_VERSION: '3.1.2'
        BUNDLER_VERSION: '2.3.19'
    entrypoint: ./docker-entrypoint.sh
    command: bash -c "bundle exec rails s -b 0.0.0.0 -p 3000"
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - bundle:/bundle
  db:
    image: postgres:latest
    volumes:
     - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
volumes:
  bundle:
  db:
