version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        taskDefinition: "arn:aws:ecs:*:*:task-definition/*"
        LoadBalancerInfo:
          ContainerName: paapi
          ContainerPort: 3000
