---
openapi: 3.0.1
info:
  title: Planning Applications API
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  '/api/v1/planning_applications':
    get:
      summary: Retrieves all planning applications
      tags:
        - Planning application
      parameters:
        - in: path
          name: uprn
          required: false
          schema:
            type: string
            minimum: 1
          description: The uprn of property's planning application
      responses:
        '200':
          description: All planning applications
          content:
            application/json:
              examples:
                Sample:
                  value:
                    data:
                      - id: 1
                        reference: 89/00090/APPLIC
                        area: South & East
                        proposal_details: Listed Building Application for replacement non-illuminated fascia sign.
                        received_at: 1900-01-01T00:00:00Z
                        officer_name: null
                        decision: Conditional permission
                        decision_issued_at: 4989-04-13T00:00:00Z
                        local_authority: buckinghamshire
                        created_at: 2022-09-22T15:12:13Z
                        view_documents: https://pa.chilternandsouthbucks.gov.uk/online-applications/applicationDetails.do?activeTab=documents&keyVal=ZZZZZYESPM408
                        property:
                          uprn: 100080483593
                          code: CR08
                          type: Commercial, Retail, Shops and Showrooms
                        address: 9 London End Beaconsfield Buckinghamshire HP9 2HN
                      - id: 3,
                        reference: 22/00836/ALB
                        area: North & Central
                        proposal_details: Listed building application for formalisation of works previously undertaken and alterations to interior and exterior of barn (retrospective)
                        received_at: 2022-03-08T00:00:00Z
                        officer_name: Anna Souter
                        decision: Listed Building Consent
                        decision_issued_at: 2022-09-20T00:00:00Z
                        local_authority: buckinghamshire
                        created_at: 2022-09-22T15:12:13Z
                        view_documents: https://publicaccess.aylesburyvaledc.gov.uk/online-applications/applicationDetails.do?activeTab=documents&keyVal=R8FT58CLG3N00
                        property:
                          uprn: 000766310186
                          code: RD03
                          type: Residential, Dwellings, Semi-Detached
                        address: Byre House Dollicott Haddenham Buckinghamshire HP17 8JG
