---
openapi: 3.0.1
info:
  title: Planning Applications API
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  $ref: './planning_applications.yaml'
